# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClassificationWithBSDD
                                 A QGIS plugin
 Use the buildingSMART Data Dictionary (bSDD) to classify features and add attributes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-29
        copyright            : (C) 2024 by Sebastian Schilling, HTW Dresden
        email                : sebastian.schilling@htw-dresden.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ClassificationWithBSDD class from file ClassificationWithBSDD.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .classification_with_bsdd import ClassificationWithBSDD
    return ClassificationWithBSDD(iface)
